options:
  formatter: stylish
files:
  include: 'source/**/*.s+(a|c)ss'
  ignore:
    - 'source/css/scss/00-abstracts/_mixins.scss'
    - 'source/css/scss/02-base/_main.scss'
    - 'source/css/scss/02-base/_normalize.scss'
    - 'source/css/scss/05-utilities/_spacing.scss'
    - 'source/css/scss/05-utilities/_utilities.scss'
    - 'source/css/scss/06-vendor/**/*.scss'
    - 'source/css/scss/07-vendor-extensions/**/*.scss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 0 # sorting up to logical order

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2 # cleaner code with
  single-line-per-selector: 0 # allow depending on length of selectors

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0 # we use hex
  no-color-keywords: 2
  no-color-literals: 1 # use variables for colors
  no-combinators: 0 # allows selecting parent child
  no-css-comments: 0
  no-debug: 0
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1 # need off for empty scss file bug
  no-extends: 1 # some cases we need for clearfix
  no-ids: 2
  no-important: 2 # only use when absolutely necessary
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 0 # allow qualifying elements with classes
  no-trailing-whitespace: 2
  no-trailing-zero: 2 # don't allow trailing 0
  no-transition-all: 1
  no-universal-selectors: 1 # only use when absolutely necessary
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 2
  property-units: 0

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 0
  force-element-nesting: 0 # allow non-nested selectors
  force-pseudo-nesting: 0 # allow non-nested pseudo selectors

  # Name Formats
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  function-name-format: 1
  id-name-format: 2
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  attribute-quotes: 2
  bem-depth: 2
  border-zero: 2
  brace-style: 2
  clean-import-paths: 2
  empty-args: 1
  hex-length:
    - 2
    -
      style: long
  hex-notation: 2
  indentation: 2
  leading-zero:
    - 2
    -
      include: true
  max-line-length:
    - 1
    -
      length: 120
  max-file-line-count: 1
  nesting-depth: 0
  property-sort-order: 0 # we use our own sort order
  pseudo-element: 2
  quotes:
    - 2
    -
      style: single
  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2 # cleaner code
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 0
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
